import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

function requireServer(secret: string) { if (!process.env.ADMIN_API_SECRET || secret !== process.env.ADMIN_API_SECRET) throw new Error("Unauthorized"); }

export const byBookingId = query({ args: { secret: v.string(), bookingId: v.string() }, handler: async (ctx, args) => { requireServer(args.secret); return ctx.db.query("bookings").withIndex("by_booking_id", (q) => q.eq("bookingId", args.bookingId)).unique(); } });

export const upsert = mutation({
  args: { bookingId: v.string(), externalId: v.optional(v.string()), firstName: v.string(), lastName: v.string(), company: v.string(), role: v.string(), country: v.string(), locale: v.union(v.literal("es"), v.literal("en")), email: v.string(), phone: v.string(), processingConsent: v.boolean(), recordingConsent: v.boolean(), start: v.string(), timezone: v.string(), channel: v.union(v.literal("web"), v.literal("phone")), status: v.string(), createdAt: v.number() },
  handler: async (ctx, args) => {
    const current = await ctx.db.query("bookings").withIndex("by_booking_id", (q) => q.eq("bookingId", args.bookingId)).unique();
    if (current) { await ctx.db.patch(current._id, { externalId: args.externalId, status: args.status, updatedAt: args.createdAt }); return current._id; }
    const leadId = await ctx.db.insert("leads", { bookingId: args.bookingId, firstName: args.firstName, lastName: args.lastName, company: args.company, role: args.role, country: args.country, locale: args.locale, email: args.email, phone: args.phone, source: "scheduled-assessment", status: args.status, processingConsentAt: args.createdAt, leadExpiresAt: args.createdAt + 365 * 86400000, createdAt: args.createdAt, updatedAt: args.createdAt });
    return ctx.db.insert("bookings", { bookingId: args.bookingId, externalId: args.externalId, leadId, start: args.start, timezone: args.timezone, channel: args.channel, status: args.status, recordingConsentAt: args.recordingConsent ? args.createdAt : undefined, createdAt: args.createdAt, updatedAt: args.createdAt, callAttempts: 0 });
  },
});

export const fromWebhook = mutation({ args: { eventId: v.string(), event: v.string(), payload: v.string(), requestId: v.optional(v.string()), receivedAt: v.number() }, handler: async (ctx, args) => { const duplicate = await ctx.db.query("webhookEvents").withIndex("by_event_id", (q) => q.eq("eventId", args.eventId)).unique(); if (duplicate) return { duplicate: true }; await ctx.db.insert("webhookEvents", { ...args, provider: "easy-appointments", status: "received", attempts: 0 }); const normalizedEvent = args.event.toLowerCase(); if (!["save", "delete"].includes(normalizedEvent)) return { ignored: true }; const payload = JSON.parse(args.payload) as { id?: number | string; appointment?: { id?: number | string } }; const externalId = String(payload.appointment?.id ?? payload.id ?? ""); if (!externalId) return { ignored: true }; const booking = await ctx.db.query("bookings").withIndex("by_external_id", (q) => q.eq("externalId", externalId)).unique(); if (booking) await ctx.db.patch(booking._id, { status: normalizedEvent === "delete" ? "cancelled" : "confirmed", updatedAt: args.receivedAt }); return { updated: Boolean(booking), externalId }; } });

export const updateCall = mutation({ args: { callSid: v.string(), status: v.string(), payload: v.string(), receivedAt: v.number() }, handler: async (ctx, args) => { const eventId = `${args.callSid}:${args.status}`; const duplicate = await ctx.db.query("webhookEvents").withIndex("by_event_id", (q) => q.eq("eventId", eventId)).unique(); if (duplicate) return; await ctx.db.insert("webhookEvents", { eventId, provider: "twilio", event: args.status, payload: args.payload, status: "received", attempts: 0, receivedAt: args.receivedAt }); const booking = await ctx.db.query("bookings").withIndex("by_call_sid", (q) => q.eq("callSid", args.callSid)).unique(); if (booking) await ctx.db.patch(booking._id, { status: `call_${args.status}`, updatedAt: args.receivedAt }); } });
