import { api } from "@/convex/_generated/api";
import { adminException, adminFailure, adminJson, authorizeContentRequest, requestId } from "@/lib/server/admin-content";
import { fetchAuthMutation, fetchAuthQuery } from "@/lib/server/auth-server";
import { providerOverrideToken } from "@/lib/server/assessment-tokens";
import { voiceProviderSchema } from "@/lib/validations/assessment";

export async function GET(request: Request) { const trace = requestId(request); try { if (!(await authorizeContentRequest(request))) return adminFailure(trace, "Unauthorized", 401); const stored = await fetchAuthQuery(api.settings.adminGet, {}); const config = stored.config as Record<string, unknown>; return adminJson(trace, { defaultProvider: config.defaultProvider || process.env.VOICE_PROVIDER || "ultravox" }); } catch (error) { return adminException(trace, "voice-settings.get", error); } }
export async function PATCH(request: Request) { const trace = requestId(request); try { if (!(await authorizeContentRequest(request))) return adminFailure(trace, "Unauthorized", 401); const parsed = voiceProviderSchema.safeParse((await request.json().catch(() => null))?.provider); if (!parsed.success) return adminFailure(trace, "Invalid provider", 400); const stored = await fetchAuthQuery(api.settings.adminGet, {}); await fetchAuthMutation(api.settings.adminSave, { config: { ...(stored.config as Record<string, unknown>), defaultProvider: parsed.data }, secrets: [] }); return adminJson(trace, { defaultProvider: parsed.data }); } catch (error) { return adminException(trace, "voice-settings.update", error); } }
export async function POST(request: Request) { const trace = requestId(request); try { if (!(await authorizeContentRequest(request))) return adminFailure(trace, "Unauthorized", 401); const parsed = voiceProviderSchema.safeParse((await request.json().catch(() => null))?.provider); if (!parsed.success) return adminFailure(trace, "Invalid provider", 400); const token = providerOverrideToken(parsed.data); const base = process.env.NEXT_PUBLIC_SITE_URL || new URL(request.url).origin; return adminJson(trace, { url: `${base}/evaluacion/ahora?provider=${encodeURIComponent(token)}` }); } catch (error) { return adminException(trace, "voice-settings.test-link", error); } }
