"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
const field = "mt-2 min-h-11 w-full rounded-lg border border-line px-3 outline-none focus:border-tech focus:ring-2 focus:ring-larimar";
export function RecoveryForm() {
  const [error, setError] = useState(""), [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); if (data.get("password") !== data.get("confirmation")) { setError("Las contraseñas no coinciden."); setLoading(false); return; } try { const response = await fetch("/api/auth/recovery", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code: data.get("code"), password: data.get("password") }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error || "No se pudo recuperar la cuenta."); return; } window.location.assign("/sign-in"); } catch { setError("No se pudo conectar con el servicio de autenticación."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="w-full rounded-2xl border border-line bg-white p-6 shadow-sm sm:p-8"><h1 className="font-display text-3xl font-bold text-primary">Recuperar acceso</h1><p className="mt-2 text-sm text-text-2">Usa uno de los códigos guardados durante la instalación.</p><label className="mt-6 block text-sm font-semibold" htmlFor="code">Código de recuperación</label><input className={field} id="code" name="code" autoComplete="one-time-code" required/><label className="mt-4 block text-sm font-semibold" htmlFor="password">Nueva contraseña</label><input className={field} id="password" name="password" type="password" autoComplete="new-password" minLength={14} required/><label className="mt-4 block text-sm font-semibold" htmlFor="confirmation">Confirmar contraseña</label><input className={field} id="confirmation" name="confirmation" type="password" autoComplete="new-password" minLength={14} required/>{error && <p role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<Button variant="dark" className="mt-6 w-full" disabled={loading}>{loading ? "Actualizando…" : "Cambiar contraseña"}</Button><Link href="/sign-in" className="mt-4 block min-h-11 py-3 text-center text-sm font-semibold text-tech">Volver al acceso</Link></form>;
}
