"use client";

import dynamic from "next/dynamic";
import { useEffect, useRef, useState } from "react";
import { Bot, ClipboardList, FileText, Loader2, LogOut } from "lucide-react";
import { authClient } from "@/lib/auth-client";

const AdminEditor = dynamic(() => import("@/components/admin/editor").then(module => module.AdminEditor), { loading: () => <AreaLoading /> });
const AssessmentAdmin = dynamic(() => import("@/components/admin/assessment-admin").then(module => module.AssessmentAdmin), { loading: () => <AreaLoading /> });
const AgentManager = dynamic(() => import("@/components/admin/agent-manager").then(module => module.AgentManager), { loading: () => <AreaLoading /> });
export type AdminArea = "assessments" | "content" | "agents";
const validArea = (value: string | null): value is AdminArea => value === "assessments" || value === "content" || value === "agents";

export function AdminWorkspace({ initialArea }: { initialArea: AdminArea }) {
  const discardDialog = useRef<HTMLDialogElement>(null);
  const editorSave = useRef<(() => Promise<boolean>) | null>(null);
  const [area, setArea] = useState<AdminArea>(initialArea), [pendingArea, setPendingArea] = useState<AdminArea | null>(null), [editorDirty, setEditorDirty] = useState(false), [savingChanges, setSavingChanges] = useState(false), [loggingOut, setLoggingOut] = useState(false), [logoutError, setLogoutError] = useState("");
  useEffect(() => { const sync = () => { const url = new URL(window.location.href), value = url.searchParams.get("area"), next = validArea(value) ? value : "assessments"; if (area === "content" && editorDirty && next !== area) { setPendingArea(next); url.searchParams.set("area", area); window.history.replaceState({}, "", url); discardDialog.current?.showModal(); return; } setArea(next); }; window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, [area, editorDirty]);
  useEffect(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (editorDirty) event.preventDefault(); }; window.addEventListener("beforeunload", beforeUnload); return () => window.removeEventListener("beforeunload", beforeUnload); }, [editorDirty]);
  function commitArea(next: AdminArea) { setArea(next); const url = new URL(window.location.href); url.searchParams.set("area", next); window.history.pushState({}, "", url); }
  function selectArea(next: AdminArea) { if (next === area) return; if (area === "content" && editorDirty) { setPendingArea(next); discardDialog.current?.showModal(); return; } commitArea(next); }
  const tab = (id: AdminArea, label: string, icon: React.ReactNode) => <button type="button" onClick={() => selectArea(id)} aria-pressed={area === id} className={`inline-flex min-h-11 shrink-0 items-center gap-2 rounded-lg px-4 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-tech ${area === id ? "bg-primary text-white" : "hover:bg-bg-2"}`}>{icon}{label}</button>;
  async function logout() { if (loggingOut) return; setLoggingOut(true); setLogoutError(""); try { const result = await authClient.signOut(); if (result.error) throw new Error(result.error.message || "No se pudo cerrar la sesión."); window.location.assign("/sign-in"); } catch (error) { setLogoutError(error instanceof Error ? error.message : "No se pudo cerrar la sesión."); setLoggingOut(false); } }
  return <div className="admin-shell"><header className="sticky top-0 z-30 border-b border-line bg-white/95 px-3 py-2 backdrop-blur sm:px-4"><div className="mx-auto flex max-w-[1600px] items-center gap-2"><nav aria-label="Secciones administrativas" className="flex min-w-0 flex-1 gap-2 overflow-x-auto">{tab("assessments", "Evaluaciones", <ClipboardList className="h-4 w-4" />)}{tab("content", "Contenido", <FileText className="h-4 w-4" />)}{tab("agents", "Agentes", <Bot className="h-4 w-4" />)}</nav><button type="button" onClick={() => void logout()} disabled={loggingOut} className="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-lg px-3 text-sm font-semibold hover:bg-bg-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-tech disabled:opacity-60 sm:px-4">{loggingOut ? <Loader2 className="h-4 w-4 animate-spin" /> : <LogOut className="h-4 w-4" />}<span className="hidden sm:inline">{loggingOut ? "Saliendo…" : "Salir"}</span></button></div>{logoutError ? <p role="alert" className="mx-auto mt-2 max-w-[1600px] rounded-lg bg-red-50 px-3 py-2 text-sm text-red-900">{logoutError}</p> : null}</header>
    {area === "assessments" ? <AssessmentAdmin /> : area === "content" ? <AdminEditor onDirtyChange={setEditorDirty} saveRef={editorSave} /> : <AgentManager />}
    <dialog ref={discardDialog} className="fixed inset-0 z-50 m-auto w-full max-w-md rounded-2xl bg-white p-6 shadow-xl backdrop:bg-primary/70"><h2 className="font-display text-xl font-bold text-primary">Cambios sin guardar</h2><p className="mt-3 text-text-2">Guarda, descarta o cancela antes de cambiar de sección.</p><div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" disabled={savingChanges} className="min-h-11 rounded-lg border border-line px-4 font-semibold disabled:opacity-60" onClick={() => { setPendingArea(null); discardDialog.current?.close(); }}>Cancelar</button><button type="button" disabled={savingChanges} className="min-h-11 rounded-lg border border-line px-4 font-semibold disabled:opacity-60" onClick={() => { if (pendingArea) commitArea(pendingArea); setEditorDirty(false); setPendingArea(null); discardDialog.current?.close(); }}>Descartar</button><button type="button" disabled={savingChanges} className="min-h-11 rounded-lg bg-primary px-4 font-semibold text-white disabled:opacity-60" onClick={() => { void (async () => { setSavingChanges(true); const saved = await editorSave.current?.(); setSavingChanges(false); if (saved && pendingArea) { commitArea(pendingArea); setPendingArea(null); discardDialog.current?.close(); } })(); }}>{savingChanges ? "Guardando…" : "Guardar y cambiar"}</button></div></dialog></div>;
}
function AreaLoading() { return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-tech" /><span className="sr-only">Cargando sección</span></div>; }
